### ISSUE TITLE
Determine Database Schema, Calculate Database Size

### ISSUE THREAD

**Issue by sahwho** [blairbasheng/quotes#1]
Start by reading: https://www.educative.io/blog/what-are-database-schemas-examples

This resource is also good: https://dba.stackexchange.com/questions/18607/how-to-estimate-database-size-needed 

Using a reference like https://www.w3schools.com/sql/sql_datatypes.asp, determine the schema (aka data type for each column) that we'll use for our SQL database of quotes that have already been scraped from BlairBash (csv file available here: https://raw.githubusercontent.com/blairbasheng/quotes/main/quotes.csv). 

Do a rough estimate of the "size" of the database (MB).

**Comment by cemeterysummoning** [comment]
Schema: 
timestamp: DATETIME (8 bytes)
score: SMALLINT (2 bytes)
votes: UNSIGNED SMALLINT (2 bytes)
quote: NVARCHAR (4 bytes + 170 bytes/character on average)
note: NVARCHAR (4 bytes + 21 bytes/character on average)
tags: NVARCHAR (4 bytes + 18 bytes/character on average)


Size per row: 233 bytes
Total rows: 9559

Total size: 9559 * 233 = 2.23 MB
