### ISSUE TITLE
File Postprocessing

### ISSUE THREAD

**Issue by sahwho** [blairbasheng/quotes#6]

**Comment by sahwho** [comment]
Postprocess the CSV file (https://raw.githubusercontent.com/blairbasheng/quotes/main/quotes.csv) to:

- escape single quotes (that are used in quote/note/tag field, for example contractions as part of the quote). To escape for SQL, should be prefixed with another single quote (not a backslash)
- convert the date field into something that can be processed (https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-timestamp/)
- convert double quotes into single quotes, since it appears SQL requires single quotes around text that will be entered into the columns. This should happen **after** the single quotes are escaped, otherwise we'll wind up converting double quotes into single quotes first and then escaping them, which we don't want to happen.

**Comment by cemeterysummoning** [comment]
After postprocessing, the file can no longer be read as a csv file, since csv files require double quotes around a string to escape commas.

**Comment by sahwho** [comment]
Completed by https://github.com/blairbasheng/quotes/pull/9
